### PR TITLE
Limit localizations populate

### PR DESCRIPTION
**Pull request by frdteknikelektro**
As for Strapi v4, `localizations` get recursively unnecessary fetch.
Trying to limit it

### CODE REVIEW

**Comment by Barelydead** [comment]
Hi, thanks for the PR! I will be looking in to merging this  and releasing a new version in the near future

**Comment by beebop1032** [comment]
Hi @Barelydead, its awesome. This fix saves a lot of time on API calls. Is it possible to implement it quickly?

**Comment by Barelydead** [comment]
This is now released on v1.0.0 @beebop1032 @frdteknikelektro

**Comment by beebop1032** [comment]
Thanks a lot !Le 7 oct. 2022 à 18:09, Christofer Jungberg ***@***.***> a écrit :﻿
This is now released on v1.0.0 @beebop1032 @frdteknikelektro

**Pull request merged**
