### PR TITLE
fix: self-recursion

### PR DESCRIPTION
**Pull request by ChrisKru97**

### CODE REVIEW

**Comment by rickylabs** [comment]
Can someone review this PR please ?

**Review by Djazz1995 — APPROVED** [review]

**Review by AliRafay — APPROVED** [review]
this works, please merge

**Comment by xyrolle** [comment]
I need it as well. Please take a look and merge.

**Review by Barelydead — APPROVED** [review]

**Comment by Barelydead** [comment]
Thanks a lot for creating the PR. Sorry for the long delay in review! Merging now and creating a release 💯

**Comment by pmig** [comment]
@Barelydead please also check https://github.com/Barelydead/strapi-plugin-populate-deep/pull/37 thanks :pray:

**Pull request merged**
